# Generated by Django 5.2.8 on 2026-03-27 06:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancereview',
            name='test_session',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test_session',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='user',
        ),
        migrations.CreateModel(
            name='StudentTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Assessment ID')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Session Key')),
                ('topic', models.CharField(max_length=200, verbose_name='Test Topic')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10, verbose_name='Initial Difficulty')),
                ('final_difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10, null=True, verbose_name='Final Difficulty')),
                ('total_questions', models.IntegerField(default=20, verbose_name='Total Questions')),
                ('answered_questions', models.IntegerField(default=0, verbose_name='Questions Answered')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Correct Answers')),
                ('wrong_answers', models.IntegerField(default=0, verbose_name='Wrong Answers')),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score Percentage')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Test Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Test End Time')),
                ('time_taken_seconds', models.IntegerField(default=0, verbose_name='Time Taken (Seconds)')),
                ('time_per_question', models.JSONField(blank=True, default=list, verbose_name='Time Per Question (Seconds)')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('auto_submitted', 'Auto Submitted'), ('expired', 'Expired')], default='in_progress', max_length=20, verbose_name='Test Status')),
                ('answers_data', models.JSONField(blank=True, default=list, verbose_name='Answers Data')),
                ('adaptive_analysis', models.JSONField(blank=True, default=list, verbose_name='Adaptive Analysis Results')),
                ('difficulty_progression', models.JSONField(blank=True, default=list, verbose_name='Difficulty Progression')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Test Result',
                'verbose_name_plural': 'Student Test Results',
                'db_table': 'student_test_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(verbose_name='Question Number')),
                ('question_text', models.TextField(verbose_name='Question Text')),
                ('options', models.JSONField(default=list, verbose_name='Question Options')),
                ('selected_answer', models.CharField(max_length=500, verbose_name='Selected Answer')),
                ('correct_answer', models.CharField(max_length=500, verbose_name='Correct Answer')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct')),
                ('time_taken_seconds', models.IntegerField(default=0, verbose_name='Time Taken (Seconds)')),
                ('predicted_difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10, null=True, verbose_name='Predicted Difficulty')),
                ('next_difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10, null=True, verbose_name='Next Difficulty')),
                ('crew_reasoning', models.TextField(blank=True, verbose_name='CrewAI Reasoning')),
                ('crew_recommendation', models.TextField(blank=True, verbose_name='CrewAI Recommendation')),
                ('full_analysis', models.TextField(blank=True, verbose_name='Full Analysis')),
                ('explanation', models.TextField(blank=True, verbose_name='Question Explanation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_performances', to='app.studenttestresult')),
            ],
            options={
                'verbose_name': 'Question Performance',
                'verbose_name_plural': 'Question Performances',
                'db_table': 'question_performances',
                'ordering': ['test_result', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='AdaptiveLearningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(verbose_name='Question Number')),
                ('current_difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10, verbose_name='Current Difficulty')),
                ('next_difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10, verbose_name='Next Difficulty')),
                ('was_correct', models.BooleanField(default=False, verbose_name='Answer Was Correct')),
                ('time_taken_seconds', models.IntegerField(default=0, verbose_name='Time Taken (Seconds)')),
                ('reasoning', models.TextField(blank=True, verbose_name='Adaptive Reasoning')),
                ('recommendation', models.TextField(blank=True, verbose_name='Recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_history', to='app.studenttestresult')),
            ],
            options={
                'verbose_name': 'Adaptive Learning History',
                'verbose_name_plural': 'Adaptive Learning Histories',
                'db_table': 'adaptive_learning_history',
                'ordering': ['test_result', 'question_number'],
            },
        ),
        migrations.DeleteModel(
            name='PerformanceMetric',
        ),
        migrations.DeleteModel(
            name='PerformanceReview',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='TestSession',
        ),
        migrations.AddIndex(
            model_name='studenttestresult',
            index=models.Index(fields=['assessment_id'], name='student_tes_assessm_9651f5_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttestresult',
            index=models.Index(fields=['user', '-created_at'], name='student_tes_user_id_96332b_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttestresult',
            index=models.Index(fields=['session_key', '-created_at'], name='student_tes_session_010b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttestresult',
            index=models.Index(fields=['topic', 'difficulty'], name='student_tes_topic_84277f_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttestresult',
            index=models.Index(fields=['status'], name='student_tes_status_330762_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionperformance',
            unique_together={('test_result', 'question_number')},
        ),
    ]
